// client/src/classes/constants.js
export const BOUNTY_VALUE = 100;
export const WEAPON_CONFIGS = {
  default: {
    name: "Machine Gun",
    category: "primary",
    modelPath: "/assets/models/guns/gun.glb",  // ✅ Matches gun.glb
    handleObject: "Object_597",
    ammo: 12,
    maxAmmo: 12,
    damage: 50,
    reloadTime: 1.5,
    fireRate: 0.3,
    range: 100,
    accuracy: 0.95,
    weight: 1.0,
    recoil: 0.1,
    muzzleFlashSize: 0.2,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.05,
    sound: "pistol_shot",
    bulletSpeed: 50,
    bulletSize: 0.05,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: -0.1, y: 1.2, z: 0 },
    fireMode: "auto",
    triggerType: "hold",
  },

  desert_eagle: {
    name: "Desert Eagle",
    category: "sidearm",
    modelPath: "/assets/models/guns/desert_eagle.glb",  // ✅ Matches desert_eagle.glb
    handleObject: "Object_118",
    ammo: 7,
    maxAmmo: 7,
    damage: 85,
    reloadTime: 2.0,
    fireRate: 0.4,
    range: 80,
    accuracy: 0.85,
    weight: 1.5,
    recoil: 0.3,
    muzzleFlashSize: 0.3,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.08,
    sound: "deagle_shot",
    bulletSpeed: 70,
    bulletSize: 0.07,
    bulletColor: 0xfdda0d,
    scale: 1.3,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "semi",
    triggerType: "click",
  },

  dragunov: {
    name: "Dragunov",
    category: "primary",
    modelPath: "/assets/models/guns/dragunov.glb",  // ✅ Matches dragunov.glb
    handleObject: "Object_74",
    ammo: 10,
    maxAmmo: 10,
    damage: 100,
    reloadTime: 3.0,
    fireRate: 1.0,
    range: 200,
    accuracy: 0.98,
    weight: 2.5,
    recoil: 0.5,
    muzzleFlashSize: 0.4,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.1,
    sound: "sniper_shot",
    bulletSpeed: 120,
    bulletSize: 0.09,
    bulletColor: 0xfdda0d,
    scale: 1.2,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "semi",
    triggerType: "click",
  },

  glock: {
    name: "Glock",
    category: "sidearm",
    modelPath: "/assets/models/guns/glock.glb",  // ✅ Matches glock.glb
    handleObject: "Object_95",
    ammo: 17,
    maxAmmo: 17,
    damage: 35,
    reloadTime: 1.2,
    fireRate: 0.2,
    range: 60,
    accuracy: 0.9,
    weight: 0.8,
    recoil: 0.08,
    muzzleFlashSize: 0.15,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.04,
    sound: "glock_shot",
    bulletSpeed: 45,
    bulletSize: 0.04,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "semi",
    triggerType: "click",
  },

  lugar: {
    name: "Luger",
    category: "sidearm",
    modelPath: "/assets/models/guns/lugar.glb",  // ✅ Matches lugar.glb
    handleObject: "Object_111",
    ammo: 8,
    maxAmmo: 8,
    damage: 40,
    reloadTime: 2.5,
    fireRate: 0.5,
    range: 70,
    accuracy: 0.88,
    weight: 1.2,
    recoil: 0.15,
    muzzleFlashSize: 0.25,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.06,
    sound: "luger_shot",
    bulletSpeed: 48,
    bulletSize: 0.06,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "semi",
    triggerType: "click",
  },

  m40: {
    name: "M40",
    category: "primary",
    modelPath: "/assets/models/guns/M40.glb",  // ✅ Fixed: M40.glb (capital M)
    handleObject: "Object_66",
    ammo: 5,
    maxAmmo: 5,
    damage: 120,
    reloadTime: 3.5,
    fireRate: 1.5,
    range: 180,
    accuracy: 0.99,
    weight: 3.0,
    recoil: 0.6,
    muzzleFlashSize: 0.5,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.12,
    sound: "m40_shot",
    bulletSpeed: 110,
    bulletSize: 0.1,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "bolt",
    triggerType: "delay",
  },

  pump_action: {
    name: "Pump Action",
    category: "primary",
    modelPath: "/assets/models/guns/pump_action.glb",  // ✅ Matches pump_action.glb
    handleObject: "Object_49",
    ammo: 6,
    maxAmmo: 6,
    damage: 60,
    reloadTime: 4.0,
    fireRate: 1.2,
    range: 40,
    accuracy: 0.7,
    weight: 2.0,
    recoil: 0.4,
    muzzleFlashSize: 0.35,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.09,
    sound: "shotgun_shot",
    bulletSpeed: 35,
    bulletSize: 0.08,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    spread: 0.2,
    pellets: 8,
    fireMode: "pump",
    triggerType: "delay",
  },

  revolver: {
    name: "Revolver",
    category: "sidearm",
    modelPath: "/assets/models/guns/Revolver.glb",  // ✅ Fixed: Revolver.glb (capital R)
    handleObject: "Object_98",
    ammo: 6,
    maxAmmo: 6,
    damage: 75,
    reloadTime: 2.8,
    fireRate: 0.6,
    range: 75,
    accuracy: 0.92,
    weight: 1.3,
    recoil: 0.25,
    muzzleFlashSize: 0.28,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.07,
    sound: "revolver_shot",
    bulletSpeed: 55,
    bulletSize: 0.065,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "semi",
    triggerType: "click",
  },

  shotgun: {
    name: "Shotgun",
    category: "sidearm",
    modelPath: "/assets/models/guns/shotgun.glb",  // ✅ Matches shotgun.glb
    handleObject: "Object_58",
    ammo: 2,
    maxAmmo: 2,
    damage: 80,
    reloadTime: 3.2,
    fireRate: 1.0,
    range: 30,
    accuracy: 0.65,
    weight: 2.2,
    recoil: 0.45,
    muzzleFlashSize: 0.4,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.1,
    sound: "shotgun_shot",
    bulletSpeed: 30,
    bulletSize: 0.09,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    spread: 0.25,
    pellets: 12,
    fireMode: "pump",
    triggerType: "delay",
  },

  // Add additional weapons from your folder
  ak47: {
    name: "AK47",
    category: "primary",
    modelPath: "/assets/models/guns/AK47_131.glb",  // ✅ Added AK47
    handleObject: "Object_??",
    ammo: 30,
    maxAmmo: 30,
    damage: 45,
    reloadTime: 2.5,
    fireRate: 0.1,
    range: 100,
    accuracy: 0.85,
    weight: 1.8,
    recoil: 0.25,
    muzzleFlashSize: 0.3,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.08,
    sound: "ak47_shot",
    bulletSpeed: 60,
    bulletSize: 0.06,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "auto",
    triggerType: "hold",
  },

  kriss_vector: {
    name: "Kriss Vector",
    category: "primary",
    modelPath: "/assets/models/guns/Kriss_Vector1.glb",  // ✅ Added Kriss Vector
    handleObject: "Object_??",
    ammo: 25,
    maxAmmo: 25,
    damage: 35,
    reloadTime: 2.2,
    fireRate: 0.08,
    range: 80,
    accuracy: 0.9,
    weight: 1.5,
    recoil: 0.15,
    muzzleFlashSize: 0.25,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.06,
    sound: "vector_shot",
    bulletSpeed: 65,
    bulletSize: 0.05,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "auto",
    triggerType: "hold",
  },

  m16: {
    name: "M16",
    category: "primary",
    modelPath: "/assets/models/guns/M161.glb",  // ✅ Added M16
    handleObject: "Object_??",
    ammo: 30,
    maxAmmo: 30,
    damage: 40,
    reloadTime: 2.4,
    fireRate: 0.09,
    range: 120,
    accuracy: 0.92,
    weight: 1.7,
    recoil: 0.2,
    muzzleFlashSize: 0.28,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.07,
    sound: "m16_shot",
    bulletSpeed: 70,
    bulletSize: 0.06,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "auto",
    triggerType: "hold",
  },

  mp5: {
    name: "MP5",
    category: "primary",
    modelPath: "/assets/models/guns/MP51.glb",  // ✅ Added MP5
    handleObject: "Object_??",
    ammo: 30,
    maxAmmo: 30,
    damage: 32,
    reloadTime: 2.0,
    fireRate: 0.07,
    range: 70,
    accuracy: 0.88,
    weight: 1.3,
    recoil: 0.12,
    muzzleFlashSize: 0.22,
    muzzleFlashColor: 0xfdda0d,
    muzzleFlashDuration: 0.05,
    sound: "mp5_shot",
    bulletSpeed: 55,
    bulletSize: 0.05,
    bulletColor: 0xfdda0d,
    scale: 1.5,
    rotation: { x: Math.PI / 2, y: Math.PI, z: Math.PI / 2 },
    position: { x: 0.2, y: 0.7, z: 0 },
    fireMode: "auto",
    triggerType: "hold",
  },
};